StuffApp/Controllers/PostStatusesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StuffApp.Models;
using StuffApp.Models.Data;

namespace StuffApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class PostStatusesController : Controller
    {
        private readonly AppCtx _context;

        public PostStatusesController(AppCtx context)
        {
            _context = context;
        }

        // GET: PostStatuses
        public async Task<IActionResult> Index()
        {
            return _context.PostStatus != null ? 
                          View(await _context.PostStatus.OrderBy(f => f.Id).ToListAsync()) :
                          Problem("Entity set 'AppCtx.PostStatus'  is null.");
        }

        // GET: PostStatuses/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null || _context.PostStatus == null)
            {
                return NotFound();
            }

            var postStatus = await _context.PostStatus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (postStatus == null)
            {
                return NotFound();
            }

            return View(postStatus);
        }

        // GET: PostStatuses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PostStatuses/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StatusName")] PostStatus postStatus)
        {
            if (_context.PostStatus
                .Where(f => f.StatusName == postStatus.StatusName)
                .FirstOrDefault() != null
                )
            {
                ModelState.AddModelError("", "Введеная категория уже существует");
            }
            if (ModelState.IsValid)
            {
                _context.Add(postStatus);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(postStatus);
        }

        // GET: PostStatuses/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null || _context.PostStatus == null)
            {
                return NotFound();
            }

            var postStatus = await _context.PostStatus.FindAsync(id);
            if (postStatus == null)
            {
                return NotFound();
            }
            return View(postStatus);
        }

        // POST: PostStatuses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, [Bind("Id,StatusName")] PostStatus postStatus)
        {
            if (id != postStatus.Id)
            {
                return NotFound();
            }

            if (_context.PostStatus
                .Where(f => f.StatusName == postStatus.StatusName)
                .FirstOrDefault() != null
                )
            {
                ModelState.AddModelError("", "Введеная категория уже существует");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(postStatus);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostStatusExists(postStatus.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(postStatus);
        }

        // GET: PostStatuses/Delete/5
        public async Task<IActionResult> Delete(short? id)
        {
            if (id == null || _context.PostStatus == null)
            {
                return NotFound();
            }

            var postStatus = await _context.PostStatus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (postStatus == null)
            {
                return NotFound();
            }

            return View(postStatus);
        }

        // POST: PostStatuses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short id)
        {
            if (_context.PostStatus == null)
            {
                return Problem("Entity set 'AppCtx.PostStatus'  is null.");
            }
            var postStatus = await _context.PostStatus.FindAsync(id);
            if (postStatus != null)
            {
                _context.PostStatus.Remove(postStatus);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostStatusExists(short id)
        {
          return (_context.PostStatus?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

StuffApp/Controllers/PostsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using StuffApp.Models;
using StuffApp.Models.Data;
using StuffApp.ViewModels.Posts;
using System.Data;

namespace StuffApp.Controllers
{
    public class PostsController : Controller
    {
        private readonly AppCtx _context;
        private readonly UserManager<User> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PostsController(AppCtx context, UserManager<User> user, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _userManager = user;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Posts
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? categoryId)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["CurrentFilter"] = searchString;
            ViewData["PageNumber"] = pageNumber != null ? pageNumber : 1;
            ViewData["CategoryId"] = categoryId;
            ViewBag.Categories = _context.Categories.ToList();
            ViewData["sortOrder"] = sortOrder;
            List<SelectListItem> orderByList = new List<SelectListItem>
            {
                new SelectListItem { Value = "name", Text = "По названию" },
                new SelectListItem { Value = "nameDesc", Text = "По названию (по убыванию)" },
                new SelectListItem { Value = "price", Text = "По цене" },
                new SelectListItem { Value = "priceDesc", Text = "По цене (по убыванию)" },
                new SelectListItem { Value = "date", Text = "Сначала старые" },
                new SelectListItem { Value = "dateDesc", Text = "Сначала новые" }
            };
            ViewBag.OrderBy = new SelectList(orderByList, "Value", "Text");

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            var appCtx = _context.Posts
            .Include(post => post.Category)
            .Include(post => post.User)
            .Select(post => new PostWithStatus
            {
                Post = post,
                LatestStatus = post.PostStatusLog
                    .OrderByDescending(log => log.EditDate)
                    .FirstOrDefault().PostStatus,
                EditDate = post.PostStatusLog
                    .OrderByDescending(log => log.EditDate)
                    .FirstOrDefault().EditDate,
                FirstImage = post.PostImage
                .OrderBy(img => img.Id)
                .FirstOrDefault().ImgUrl
            })
            .Where(postWithStatus => postWithStatus.LatestStatus.Id == 3); ;
            if (categoryId.HasValue)
            {
                appCtx = appCtx.Where(post => post.Post.IdCategory == categoryId.Value);
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                appCtx = appCtx.Where(s => s.Post.Title.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "nameDesc":
                    appCtx = appCtx.OrderByDescending(s => s.Post.Title);
                    break;
                case "price":
                    appCtx = appCtx.OrderBy(s => s.Post.Price);
                    break;
                case "priceDesc":
                    appCtx = appCtx.OrderByDescending(s => s.Post.Price);
                    break;
                case "date":
                    appCtx = appCtx.OrderBy(s => s.EditDate);
                    break;
                case "dateDesc":
                    appCtx = appCtx.OrderByDescending(s => s.EditDate);
                    break;
                default:
                    appCtx = appCtx.OrderBy(s => s.Post.Title);
                    break;
            }

            int pageSize = 4;
            return View(await PaginatedList<PostWithStatus>.CreateAsync(appCtx.AsNoTracking(), pageNumber ?? 1, pageSize));
        }
        [Authorize(Roles = "registeredUser, admin")]
        public async Task<IActionResult> IndexMy(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? categoryId, short? statusId)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["CurrentFilter"] = searchString;
            ViewData["PageNumber"] = pageNumber != null ? pageNumber : 1;
            ViewData["CategoryId"] = categoryId;
            ViewBag.Categories = _context.Categories.ToList();
            ViewData["sortOrder"] = sortOrder;
            List<SelectListItem> orderByList = new List<SelectListItem>
            {
                new SelectListItem { Value = "name", Text = "По названию" },
                new SelectListItem { Value = "nameDesc", Text = "По названию (по убыванию)" },
                new SelectListItem { Value = "price", Text = "По цене" },
                new SelectListItem { Value = "priceDesc", Text = "По цене (по убыванию)" },
                new SelectListItem { Value = "date", Text = "Сначала старые" },
                new SelectListItem { Value = "dateDesc", Text = "Сначала новые" }
            };
            ViewBag.OrderBy = new SelectList(orderByList, "Value", "Text");
            ViewData["StatusId"] = statusId;
            List<SelectListItem> statusesList = new List<SelectListItem>
            {
                new SelectListItem { Value = "3", Text = "Опубликованные" },
                new SelectListItem { Value = "2", Text = "На модерации" },
                new SelectListItem { Value = "1", Text = "Черновики" },
            };
            ViewBag.StatusesList = new SelectList(statusesList, "Value", "Text");
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            var currentUserId = _userManager.GetUserId(User);
            var appCtx = _context.Posts
            .Include(post => post.Category)
            .Include(post => post.User)
            .Where(post => post.IdUser == currentUserId)
            .Select(post => new PostWithStatus
            {
                Post = post,
                LatestStatus = post.PostStatusLog
                    .OrderByDescending(log => log.EditDate)
                    .FirstOrDefault().PostStatus,
                EditDate = post.PostStatusLog
                    .OrderByDescending(log => log.EditDate)
                    .FirstOrDefault().EditDate,
                FirstImage = post.PostImage
                .OrderBy(img => img.Id)
                .FirstOrDefault().ImgUrl
            });
            if (categoryId.HasValue)
            {
                appCtx = appCtx.Where(post => post.Post.IdCategory == categoryId.Value);
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                appCtx = appCtx.Where(s => s.Post.Title.Contains(searchString));
            }
            if (statusId.HasValue)
            {
                appCtx = appCtx.Where(s => s.LatestStatus.Id == statusId.Value);
            }
            else
            {
                appCtx = appCtx.Where(s => s.LatestStatus.Id == 3);
                ViewData["StatusId"] = 3;
            }
            switch (sortOrder)
            {
                case "nameDesc":
                    appCtx = appCtx.OrderByDescending(s => s.Post.Title);
                    break;
                case "price":
                    appCtx = appCtx.OrderBy(s => s.Post.Price);
                    break;
                case "priceDesc":
                    appCtx = appCtx.OrderByDescending(s => s.Post.Price);
                    break;
                case "date":
                    appCtx = appCtx.OrderBy(s => s.EditDate);
                    break;
                case "dateDesc":
                    appCtx = appCtx.OrderByDescending(s => s.EditDate);
                    break;
                default:
                    appCtx = appCtx.OrderBy(s => s.Post.Title);
                    break;
            }


            int pageSize = 8;
            return View(await PaginatedList<PostWithStatus>.CreateAsync(appCtx.AsNoTracking(), pageNumber ?? 1, pageSize));
        }


        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }



            var post = _context.Posts
            .Include(post => post.Category)
            .Include(post => post.User)
            .Include(post => post.PostImage)
            .Where(post => post.Id == id)
            .Select(post => new PostWithStatus
            {
                Post = post,
                LatestStatus = post.PostStatusLog
                    .OrderByDescending(log => log.EditDate)
                    .FirstOrDefault().PostStatus,
                EditDate = post.PostStatusLog
                    .OrderByDescending(log => log.EditDate)
                    .FirstOrDefault().EditDate
            })
            .FirstOrDefault();
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }
        [Authorize(Roles = "registeredUser, admin")]
        public async Task<IActionResult> DetailsModerate(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

   

            var post = _context.Posts
            .Include(post => post.Category)
            .Include(post => post.User)
            .Include(post => post.PostImage)

StuffApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/swiper.css" />
    <link rel="stylesheet" href="~/StuffApp.styles.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light bg-white border-bottom box-shadow mb-3 container-fluid justify-content-between">
            <div class="d-flex align-items-center">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StuffApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-lg-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Index">Объявления</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="SubscribeIndex">Подписки</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="IndexMy">Мои объявления</a>
                            </li>
                        }
                        @* @if (User.Claims.Where(c => c.Type == System.Security.Claims.ClaimTypes.Role).Select(s => s.Value).Contains("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Категории</a>
                            </li
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PostStatuses" asp-action="Index">Статусы объявлений</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Управление пользователями</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="IndexModerate">Модерация объявлений</a>
                            </li>
                        } *@                        
                    </ul>
                </div>
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="d-flex gap-3 align-items-center">
                    @if (User.Claims.Where(c => c.Type == System.Security.Claims.ClaimTypes.Role).Select(s => s.Value).Contains("admin"))
                    {
                        <div class="dropdown">
                            <button class="nav-link text-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Админ-панель
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Categories" asp-action="Index">Категории</a>
                                <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="PostStatuses" asp-action="Index">Статусы объявлений</a>
                                <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Users" asp-action="Index">Управление пользователями</a>
                                <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Posts" asp-action="IndexModerate">Модерация объявлений</a>
                            </div>
                        </div>
                    }
                    <span>@User.Identity.Name</span>

                    <form class="" method="post" asp-controller="Account" asp-action="Logout">
                        @* <input type="submit" value="Выход" /> *@
                        <button type="submit" class="btn btn-secondary">Выход</button>
                    </form>
                </div>
            }
            else
            {
                <div class="d-flex justify-content-end gap-3">
                    <a class="btn btn-secondary" asp-controller="Account" asp-action="Login">Вход</a>
                    <a class="btn btn-secondary" asp-controller="Account" asp-action="Register">Регистрация</a>
                </div>
    
            }
            @* <div class="ml-auto d-flex gap-2">Логин, Выход</div> *@
        </nav>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - StuffApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Политика конфиденциальности</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>